const exampleDatabase = [
  {
    name: "Test 1",
    date: "02/02/21",
    creator: "Darth Vader",
    ingredients: {},
    instructions: "Shake for 10 seconds.",
    description: "very good",
  },
  {
    name: "Test 2",
    date: "02/02/21",
    creator: "Jar Jar",
    ingredients: {},
    instructions: "Shake for 10 seconds.",
    description: "very good",
  },
  {
    name: "Test 2",
    date: "02/02/21",
    creator: "Jar Jar",
    ingredients: {},
    instructions: "Shake for 10 seconds.",
    description: "very good",
  },
  {
    name: "Test 2",
    date: "02/02/21",
    creator: "Jar Jar",
    ingredients: {},
    instructions: "Shake for 10 seconds.",
    description: "very good",
  },
  {
    name: "Test 2",
    date: "02/02/21",
    creator: "Jar Jar",
    ingredients: {},
    instructions: "Shake for 10 seconds.",
    description: "very good",
  },
  {
    name: "Test 2",
    date: "02/02/21",
    creator: "Jar Jar",
    ingredients: {},
    instructions: "Shake for 10 seconds.",
    description: "very good",
  },
  {
    name: "Test 2",
    date: "02/02/21",
    creator: "Jar Jar",
    ingredients: {},
    instructions: "Shake for 10 seconds.",
    description: "very good",
  },
  {
    name: "Test 2",
    date: "02/02/21",
    creator: "Jar Jar",
    ingredients: {},
    instructions: "Shake for 10 seconds.",
    description: "very good",
  },
  {
    name: "Test 2",
    date: "02/02/21",
    creator: "Jar Jar",
    ingredients: {},
    instructions: "Shake for 10 seconds.",
    description: "very good",
  },
  {
    name: "Test 2",
    date: "02/02/21",
    creator: "Jar Jar",
    ingredients: {},
    instructions: "Shake for 10 seconds.",
    description: "very good",
  },
]

export default exampleDatabase;
